version: '3.8'

services:
  app1:
    image: myapp:jdk17
    container_name: app1
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8081:8080"

  app2:
    image: myapp:jdk17
    container_name: app2
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8082:8080"
