version: '3.8'

services:
  app1:
    image: myapp:jdk17
    container_name: app1
    ports:
      - "8081:8080"

  app2:
    image: myapp:jdk17
    container_name: app2
    ports:
      - "8082:8080"
